### PR TITLE
trpc: rename `use*` to `create*`

### PR DESCRIPTION
**Pull request by oscartbeaumont**
This PR is majorly breaking!

I have renamed all tRPC hooks from `use*` to `create*`.

Personally, I think this fits better with Solid's naming conventions and was a point of confusion when I first used the library as I came from `@tanstack/solid-query` which uses the `create*` naming convention.

Ryan discussed how he views Solid's naming convention [here](https://github.com/solidjs/solid/issues/317#issuecomment-767715235) as well and I think based on it `create*` seems like a better move.

### CODE REVIEW

**Comment by lxsmnsyc** [comment]
Haven't seen the entire change but do take note that the `use` and `create` conventions in Solid is highly conventional and depends on grammatical context.

**Comment by oscartbeaumont** [comment]
Yeah for sure.

The tRPC bindings directly wrap the `@tanstack/solid-query` hooks which themselves use the `create*` naming convention which is why I think `create*` is more appropriate here.

We are also creating a new instance of the query on each call which is *basically* a really fancy signal/store, both of which use the `create*` convention. `use*` is more about using something created somewhere else (Eg. `useContext`).

It could possibly be argued we are using the tRPC client from the context but given it's wrapped into a unique `useQuery` instance I don't think this is fair. I also think this same argument could be applied to `@tanstack/solid-query` and they chose `create*` which is why I don't think it's fair here.

**Comment by OrJDev** [comment]
Thank you for this but this seems to conflict with your other pr regarding the re-use of the trpc client, are you able to resolve the conflicts?

**Comment by OrJDev** [comment]
> Thank you for this but this seems to conflict with your other pr regarding the re-use of the trpc client, are you able to resolve the conflicts?

Also this would be better to create at a different pull request because i just added a changeset bot that should help us here. So if you could close rhis pr and make a different one with no conflicts

**Comment by oscartbeaumont** [comment]
@OrJDev Thanks for the review. The conflict is fixed and the changeset has been added and picked up by the bot.

I didn't really wanna create another PR but if it's really required I can do so.

**Comment by OrJDev** [comment]
Awesome thank you, this will be merged when im able to update create jd app, because create jd app's trpc installer still use .use

**Pull request merged**
